### ISSUE TITLE
Send video strim link to server

### ISSUE THREAD

**Issue by iWedmak** [iamthevoid/oneom-android#1]
When user selects video stream from vodlocker, send link and ep id to server.
Post to: video/index
Fields: ep_id , url

**Comment by iamthevoid** [comment]
Must I check season/ep number of online video stream before?

**Comment by iWedmak** [comment]
im not sure i think i made some theod to add new data from user, but not sure how its gona look like, i will add extra description to this ticket in future, sooon

**Comment by iamthevoid** [comment]
Resolved
