### ISSUE TITLE
Wrong poster

### ISSUE THREAD

**Issue by iWedmak** [iamthevoid/oneom-android#7]
For  example
this tv show https://oneom.tk/serial/2227 
have this poster
http://oneom.tk/public/serial/max/2227.jpg
but in app its different, what poster path do u use?

**Comment by iamthevoid** [comment]
"serial" object - "poster" object - "original" value

**Comment by iWedmak** [comment]
link to image file goes like this
/public/{{$ep['serial']['poster']['path']}}/max/{{$ep['serial']['poster']['name']}}
+ domain
original may be different
